name: AI News Discord

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  ai-news:
    runs-on: ubuntu-latest

    steps:
      - name: Send test message to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content":"GitHub Actions接続テスト成功"}' \
          "${{ secrets.DISCORD_WEBHOOK_URL }}"
